const MIN_INSTRUMENT_DURATION_MINUTES = 15;
const ALLOWED_UNITS = ["ml", "g", "L", "units"];
const USER_ROLES = {
  ADMIN: "admin",
  USER: "user",
};
const BOOKING_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};
const RESOURCE_TYPES = {
  INSTRUMENT: "INSTRUMENT",
  MATERIAL: "MATERIAL",
};

module.exports = {
  MIN_INSTRUMENT_DURATION_MINUTES,
  ALLOWED_UNITS,
  USER_ROLES,
  BOOKING_STATUS,
  RESOURCE_TYPES,
};
